# Generated by Django 6.0.7 on 2026-07-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TTSGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('mode', models.CharField(choices=[('emotional', 'NeuTTS-2E (Emotional)'), ('cloning', 'NeuTTS Voice Cloning')], default='emotional', max_length=20)),
                ('speaker', models.CharField(blank=True, max_length=50, null=True)),
                ('emotion', models.CharField(blank=True, max_length=50, null=True)),
                ('backbone_model', models.CharField(default='neuphonic/neutts-nano', max_length=100)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='neutts_outputs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
